socrata-platform/query-coordinator

src/main/scala/com/socrata/querycoordinator/Service.scala
queryParameter doesn't handle form fields.  Need to use getParameter.
=> Need the original getParameter call to get form fields.

build.sbt, src/main/resources/reference.conf, src/main/scala/com/socrata/querycoordinator/Main.scala, src/main/scala/com/socrata/querycoordinator/QueryCoordinatorConfig.scala
so that things don't fall over in prod upon high load
=> Upgrade to socrata-http 3.3.0, use bounded queues

bin/start_qc.sh
=> * rename start_qc.sh command so it finds the right jar

query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala
This take care of cases where rollup soql is good but supporting sql asset is bad like missing rollup table.
=> Recover from bad rollups.

project/Dependencies.scala
made changes to soql-reference, making sure query coordinator is up to date.
=> EN-3726: Bump soql-reference version

query-coordinator/src/main/scala/com/socrata/querycoordinator/Main.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/SchemaFetcher.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryService.scala
Makes things less explody when something goes wrong with a secondary store.
=> Connection failure retries

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala
before (not work):
select phone, phone_number |> select * where phone = '123' =>
select phone(phone, phone) |> select * where phone = '123'
after:
select phone, phone_number |> select * where phone = '123' =>
select phone, phone_number |> select phone(phone, phone) where phone = '123'
=> EN-5371 - expand "select *" in all the chained soql.

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala
When satisfying a request from cache, if we request a block of
windows that looks like
```
[XXXXX][XXXXX][XXXXX]
^             ^
```
but what we get is
```
[XXXXX][XX   ]
```
then we shouldn't apply the `take` to the last window that we
actually get, or we can return a short read.
=> Don't short-read if more windows were requested than were present

query-coordinator/src/main/scala/com/socrata/querycoordinator/util/ConfigWatch.scala
Instead of reverting to the default, remain at the most recent valid
value if there was one.
I'll be moving this into thirdparty-utils shortly.  I really like this one.
=> Smarter behavior on bad ZK config values

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala
Where "small" is defined as "not the output of a group-by and also with
fewer than one window's worth of results".
Attempting to reduce cache-expiration CPU usage.
=> Don't try to cache small results

project/Dependencies.scala
These functions provide support for the apps team.
All is needed here is bump soql-lib.
=> EN-14870 Add date_extract_xxx(floating_timestamp) functions.

project/Dependencies.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala
The bulk of the work took place in soql-ref.
=> EN-16454 Support multiple “SELECT *”’s

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala
In order to allow using rollups to speed up common grouped queries, we want to be able to skip
doing the grouping if the rollup is already grouped the exact way the query wants.  This doesn't
matter for the smaller rollups that the code was originally designed to support but for other
uses that are large after grouping it makes a big difference.
=> EN-19215: Skip grouping when querying the rollup if it already matches the query grouping.

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala
The base case for HAVING is pretty simple, as expressions there are something
we already are mapping in the selection or grouping so they map the same way.
In the case where the grouping in the query has the exact same columns as the rollup
and we are removing the grouping, we have to move the condition into the where clause.
=> EN-19741: Add rewrite support for HAVING.

query-coordinator/src/main/resources/reference.conf, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/cache/CacheSessionProvider.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/cache/config/CacheConfig.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/cache/config/CacheSessionProviderFromConfig.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/cache/postgresql/PostgresqlCacheSessionProvider.scala
No rows is not an error.
Configure to not cache if query time is less than 3s.
=> EN-20445 Log more info.

project/Dependencies.scala
=> EN-32501: support negative number cast (from text)

project/Dependencies.scala
=> EN-33655 Add text to boolean auto cast

Jenkinsfile
Added BRANCH_SPECIFIER parameter and more detailed checkout if it is set to a non-default value
=> Allow for non-master branch builds

project/Dependencies.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/Schema.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala
Mostly around making sure not to check collocation with it
=> Handle the various single-row special cases

project/Dependencies.scala
For the new `as @tablename` syntax
=> Update soql library

project/Dependencies.scala
Adds references to new geo functions ST_Overlaps and ST_Crosses
=> update soqlstdlib dependency

project/Dependencies.scala
=> Bump soql reference to get new functions

project/Dependencies.scala
version bump for new soql functions
=> v3.13.1 of soql-stdlib

project/Dependencies.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/SoQLAnalysisDepositioner.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/fusion/CompoundTypeFuser.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryParserTest.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/fusion/CompoundTypeFuserTest.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/fusion/QueryParserFuseTest.scala
curl -v "http://localhost:6010/resource/_catx-xxxx?%24query=select+count(*)+filter(where+false)+over()"
=> EN-49288: Aggregate function call filter

project/Dependencies.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/SoQLAnalysisDepositioner.scala
SELECT col1, col2 WHERE . . . |>
SELECT HINT(materialized) col1
=> EN-49831: Support SoQL Hint

project/Dependencies.scala
SELECT avg(n)
vs
SELECT sum(n)/count(n)
vs
SELECT sum(n) as s, count(n) as c |>
SELECT hint(no_chain_merge) s/n as avg
=> EN-50821: Poor man support of rollup average

query-coordinator/src/main/scala/com/socrata/querycoordinator/CompoundQueryRewriter.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestCompoundQueryRewriterBase.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterBase.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncBase.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterWindowFunction.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestRollupScorer.scala
=> EN-52731: Rollup X Union (Compund Query)

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala
* Copy the MDC over to the worker thread
* Log any errors that are thrown instead of just letting them get printed
to stderr
=> Improve logging while caching a thing

README.md, query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewriterTest.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewritingTestUtility.scala
Existing testing was dependent on scattered static state.
This is a rewrite of that flow to make future work easier.
Still fairly complex, but usage should be easy to understand.
=> query rewrite unit testing setup for easier use without global state

.run/query-coordinator.run.xml, query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala, query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncBase.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterWindowFunction.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/TestRollupScorer.scala
- Adding merge analysis step for chained queries
- (maintenance) adding run configuration for IDEA
=> EN-56812  Rollups using chained queries do not work

query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/ExpressionRewriter.scala
=> [EN-58178] Exploration Canvas | Rollup Error | Exception: empty.reduceLeft

project/Dependencies.scala
This just tells the analyzer they're normal functions; all the interesting bits of this task are over in soql-postgres-adapter.
=> EN-58724: De-aggregate hull functions

query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewriterWindowFunctionTest.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/defect/Cheetah.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/defect/EN55220.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/defect/EN58705.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/util/MergeTest.scala, query-coordinator/src/test/scala/com/socrata/querycoordinator/util/QueryRewritingTestUtility.scala
Moved the util class to the util folder.
Added method for testing merges.
Some simple merge tests.
=> upgrading test framework to handle merge tests

Jenkinsfile
In the Jenkinsfile, on release cuts, the dockerized image deployed to RC.
In the Jenkinsfile, on release builds, the dockerized image is not deployed to RC.
Also:
- new parameter RELEASE_DRY_RUN added to ease testing
- changed stage name from "Cut" to "Release Tag"
- used simpler syntax for deploying
- simplified logic for which stage to build
=> EN-59947: update Jenkinsfile

project/Dependencies.scala
Bumping the SOQL version from 4.14.13 to 4.14.22.
=> Bump SOQL version to 4.14.22

query-coordinator/docker/ship.d/run
..by making the sandbox dir writable.
=> EN-67063: make sure heap dumps can actually be saved

project/Dependencies.scala
Bump soql to get the "`select ... from parent-view` is allowed" fix.
=> EN-75342: Bump soql

query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/NewQueryResource.scala
Specifically allow it to be one of
* never, to never automatically propagate sys cols
* always, to always do so when it doesn't change query semantics
* non_aggregated, to do so when it doesn't change query semantics _or_ through aggregates
=> EN-77403: Make "preserve system columns" more fine-grained
