socrata-platform/query-coordinator

src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTrunc.scala
src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncBase.scala
src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncLtGte.scala

We do that by looking to see if the literal value passed in is the same as
the output from a date_trunc_xxx call, and if so substituting it where
"column > literal" or "column <= literal". The forms "literal < column" and
"literal >= column" are easy to add but not implemented.
See the scaladoc for the rewriteDateTruncGteLt method in QueryRewriter for
more details.

Add support for rewriting date queries to use rollups with date_trunc_xxx columns.

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala

In the case where the query didn't have a GROUP BY on it, but the
rollup did, we could incorrectly rewrite the query to use the rollup
resulting in incorrect results if all the columns in the query are
in a rollup.
We now will only do the rewrite if all the columns are aggregates.
The Selection rewrite will ensure the aggregates can be mapped
appropriately to the rollup's Selection by either being self
aggregatable or falling into some other specific special aggregation
case.

CORE-7254: Incorrectly rewriting queries without a GROUP BY to use a grouped rollup.

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/RollupScorer.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestRollupScorer.scala

This is essentially a simple "rule based" optimizer that looks at the structure of the
rollup to assign it a score based on how expensive we think it might be to query.
We do not consider the particulars of the query, just the rollup.
Please see the docs in com.socrata.querycoordinator.RollupScorer for an explaination
of how it functions.

Add basic support for selecting the best rollup when doing query rewrite.

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/fusion/CompoundTypeFuser.scala

system columns lose their prefix ':'

Shouldn't touch columns that are not expanded.

---

query-coordinator/docker/Dockerfile

Jenkins jobs are updated to build the code with Java 8. Build passed in Jenkins and container is running fine in staging under Java 8.

EN-5910: Use Java8 base image for dockerizing query-coordinator

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala

This is excessively verbose and we have sufficient other logging
and tooling now to get info on what a queries query is from higher up
the stack.

EN-6168: Don't log the analysis for every query.

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/SoQLAnalysisDepositioner.scala

Just the one in the select level.
SELECT DISTINCT col1, col2, …
not the one inside function
SELECT COUNT(DISTINCT col1)
** DEPLOY soql-postgres-adapter BEFORE query-coordinator **
to avoid service interruption

EN-14996 Add “Distinct” support

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala

This is enough for soqls generated for default views in core server to work.
No need to skip merging whenever there are joins.

EN-16339 Make chaining/merging work with joins to some degree

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala

A count on a specific column is the number of non-null values, which can be
added together with a simple sum just like count(*).

EN-19151: Support query rewrite on count(column).

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala

b9771c7ef57615cb4dc76b23351b5ed0e399c3b3 added support for skipping
grouping when querying the rollup if the grouping was an exact
match, but we can also do it if the ordering is different.

EN-19742: Support skipping grouping even if ordering is different.

---

project/Dependencies.scala

To support definitions added by: https://github.com/socrata-platform/soql-reference/pull/92

EN-19155: Bump soqlStdlib to 2.9.1 to support new geo functions

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/caching/cache/postgresql/PostgresqlCacheSchema.scala

Exception in thread "Cache thread" org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
Detail: Key (typname, typnamespace)=(cache_alpha_103197_data, 2200) already exists.

EN-20877 Fix create cache table race issue.

---

.gitignore
configs/application.conf
configs/sample-query-coordinator.conf
configs/sample.conf
query-coordinator/src/main/resources/reference.conf

Clearly comment that it was for solo (becaus I was confused).
Also, a little bit of config renaming to match spandex based
off of code reviews there.

EN-22044: Explicit use of local.dev.socrata.net

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTrunc.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncLtGte.scala

It was getting rewritten to sum(count_column) on a rollup, but if
that rollup has no rows, the sum is null.  Wrap that expression in
a `coalesce(..., 0)` to eliminate the null

Fix count(*) on empty datasets

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/Main.scala

The CPU overhead is fairly minimal and the network cost adds up quickly.

Enable HTTP content compression on requests to soql pg server

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterWindowFunction.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestRollupScorer.scala

Window functions run after where / group by / having so can't be
rewritten in isolation.  We could still rewrite a query with a
window function in if the other clauses all match, however that
requires coordination between expression mapping and mapping other
clauses at a higher level that isn't implemented, so for now we
just forbid it entirely to avoid incorrect rewrites.

EN-40314: Don't rewrite window functions.

---

project/Dependencies.scala

it does not merge chained soql if there is search and grouping any more after the new semantics of search (application to the output schema instead of the input schema)

EN-24494: Bump soql-reference so that

---

project/Dependencies.scala

Add support for the new functions in the new SoQL Standard Lib:
`regr_slope`
`regr_intercept`
`regr_r2`
`ln`

bump soqlstdlib dependency

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala

* New error cases leftover from the introduction of `single_row`
* Joins have been slightly restructured
* Bail on join functions (since they should have been eliminated in core)

Update for changes in soql-stdlib

---

project/Dependencies.scala

Introduces:
`round(N, x)` function to round a number to the nearest x digits.
E.g.
round(3.1415, 3) => 3.142
round(315, -1) => 320

EN-46401 - bump soqlstdlib dependency

---

project/Dependencies.scala

Before:
v3.11.0
After:
v3.11.2
Supporting new SoQL Functions LEAD and LAG

use v3.11.2 of soqlstdlib

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/datetime/NowAnalyzer.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryParserTest.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/datetime/NowAnalyzerTest.scala

Which is simpler and always uses UTC.
The datetrunc logic only worked for timestamp literal approach

EN-32486: Fix datetrunc logic to work with the context variable approach

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncLtGte.scala

As a result, developers need to introduce stray group by in rollup and query like
R: 
SELECT count(x), :id is not null GROUP BY date_trunc_ymd(date), :id is not null
Q:
SELECT count:cross_mark: WHERE date >= d1 AND date < d2 GROUP BY :id is not null

EN-50984: Queries without explicit group by do not use rollups

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewriterWithJoinEnabled.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterWindowFunction.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestRollupScorer.scala
version.sbt

This is a general effort in improving query performance by supporting a wider variety of queries in rollups.
Join queries can use rollups when their joins match.
Rollup updated-ness is out of scope.  We only update rollups when the primary table is changed.  Join table change will not trigger rollup refresh.  Because of this, we limit this usage to superadmin via special request header.

EN-51750: Support join queries in rollups

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryRewriter.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala

This allow us to retry the query without rollup in case there is anything wrong with the query rewritten with rollup.  This behavior is now identical to how we handle primary rollup application.

EN-55111: Keep track of non-primary rollup application (at joins)

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryCoordinatorErrors.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/exceptions/ParameterSpecException.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryService.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/util/Join.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryParserTest.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/fusion/QueryParserFuseTest.scala

Now that we do not replace query params upstream, we need to give the analyzer context. This pr builds up the context for the analyzer, using the lens id passed from soda fountain in this pr: https://github.com/socrata-platform/soda-fountain/pull/383/files

EN-54831 - give params in context for analysis

---

.run/query-coordinator.run.xml
query-coordinator/src/main/scala/com/socrata/querycoordinator/Main.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/CompoundQueryRewriter.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/QueryRewriter.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/QueryRewriterImplementation.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/RollupInfo.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/RollupInfoFetcher.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/RollupScorer.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewriterTest.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewriterWithJoinEnabled.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewritingTestUtility.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestCompoundQueryRewriterBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterDateTruncBase.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriterWindowFunction.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestRollupScorer.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/fusion/CompoundTypeFuserTest.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/rollups/TestRollupQueryRewriter.scala

QueryRewriter is a large class and it is a dependency used by QueryResource. QueryResource only uses (and so needs to now) a few methods from QueryRewriter - i.e. an interface. It is better to separate an interface from the implementation - less coupling, clear interface definition, easier to understand code.
With readability and code organization in mind, classes related to large functional block (i.e. rollups) are better placed in a package.
The changes made in this PR:
- QueryRewriter becomes an abstract class defining the interface
- QueryRewriterImplementation implements it
- files related to the rollups moved to query coordinator.rollups 
- some utility methods moved from companion to class

NOJIRA: Separating QueryRewriter interface and implementation

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala

This can happen if the dataset is moved out from under us (e.g., because of a collocation).  This can turn a "not found" reponse into either a "ran out of retries" or a "dataset not available" if the dataset is genuinely gone - but if the dataset had been gone and not in our cache in the first place, it would've been "dataset not available" anyway.

Retry instead of failing when not found in the chosen secondary

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/ExpressionRewriter.scala
query-coordinator/src/test/resources/rollups/query_rewriter_test_configs/test_filtering.json
query-coordinator/src/test/scala/com/socrata/querycoordinator/TestQueryRewriteDateTruncViaFilter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/rollups/TestRollupQueryRewriter.scala

FILTER clause is ignored in matching count() columns in rollups, which reals to incorrect matching.

[EN-58131] filter function is incorrectly applied

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/ClauseAwareExpressionRewriter.scala
query-coordinator/src/test/scala/com/socrata/querycoordinator/QueryRewriterWindowFunctionTest.scala

Right, we should not assume rewriting is successful.
Need to wrap that new window function path in a try.

do not fail when rollup is missing window function expression

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/QueryResource.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/rollups/QueryRewriter.scala

Originally we only try to rewrite the left side of a query pipe.
Recently we introduced rollups being able to use pipes.
As result we need to handle rewriting left/right better.
EN-58705

Piped query rewriting fix

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryExecutor.scala

Just adding a field to the metric.
We have the rollup name if one was used, lets put it in the metric also.

add field to query hit for rollups

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/NewQueryResource.scala

Plumb location subcolumn info down to the secondary, after changing it from its JSON-friendly sequence-of-pairs form to a more sensible map form

EN-60548: Fake-locations on the new query path

---

Jenkinsfile
query-coordinator/build.sbt

* The filename no longer contains the version number
* The file is stored in target instead of target/scala-$version

Simplify assembly filename

---

Jenkinsfile

We use the sbt version incremented using sbt release for git tags for releases.
For deploy tags, we use the format `${env.SERVICE_VERSION}_${env.BUILD_ID}_${env.SERVICE_SHA}`.  This is for release builds as well as staging builds.
We use the release name for both the git tag and deploy tag for releases.  
For staging builds, we use the existing format with `SERVICE_VERSION = 'STAGING'`.

EN-61797: use release name as git tag and deploy tag

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/QueryParser.scala

QueryParser's limitRows function would always check for a limit on the leftmost leaf, which ran counter to Core's policy of setting the its "default" maxInt limit on the rightmost/last leaf . Because of this, QC would not see the existing default limit and would override it with its own default limit of 1000 rows. 
Fixed by changing the limitRows function to correctly look at the rightmost/last leaf when checking for an existing limit.

EN-63625: QueryParser respects passed in limit on UNIONs

---

Jenkinsfile

Because I forgot to change the RMS environment from staging to production before merging https://github.com/socrata-platform/query-coordinator/pull/360, this commit does that.

EN-62410: rms production

---

Jenkinsfile

This commit moves the release tagging after a successful docker build. In order to do this, it separates the docker build from the publishing of the images into separate Jenkinsfile steps.

EN-65713: move release tagging

---

project/Dependencies.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/Secondary.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/NewQueryResource.scala
query-coordinator/src/main/scala/com/socrata/querycoordinator/util/NewQueryError.scala
secondary-selector/src/main/scala/com/socrata/querycoordinator/SecondaryInstanceSelector.scala

Now we find all secondaries for all datasets involved in a query, intersect those sets together, and pick one at random from that intersection.
Also if we can't find a satisfactory secondary, return a real soql error.

EN-67069: Better(?) secondary-selection on the v3 path

---

Jenkinsfile

This commit pins the version for socrata-pipeline-library so that it will not break when breaking changes are added in subsequent versions.

EN-71533: pin pipelines library version

---

Jenkinsfile

This commit updates the Jenkinsfile to use the latest verison of the pipeline library, which will have the effect of publishing the image to the latest tag for each deployment to staging, which is important for our ECS migration.

EN-76223: publish to latest

---

Jenkinsfile
build.sbt

This commit transitions this repository's Jenkins job to use sbtWrapper, a replacement for the legacy sbtWrapper. sbtWrapper induces backwards incompatible changes in the common pipeline, and the major version of pipelines is accordingly bumped.

Switch to `sbtWrapper`

---

query-coordinator/src/main/scala/com/socrata/querycoordinator/resources/NewQueryResource.scala

When we're issuing a query on the new-analyzer path, if we get a connection-time error or if there are no available instances for the chosen secondary registered in the broker, then try a different secondary in addition to re-fetching a new service instance.

EN-81051: when retrying a query, allow other secondary
